[UX] Credentials window improvements
Halodi/halodi-unity-package-registry-manager pull request #17
Opened 2020-10-30 00:37 UTC by hybridherbst

This PR improves a number of smaller UX details in the credentials flow.

Notably, help boxes have been added to provide guidance on what data to fill in, and buttons are only enabled when they make sense to press.
Additionally, errors are now logged directly into the GetToken view, instead of closing the view and requiring to reopen it to try again, and the credentials view is repainted upon aquiring a token.

On 2020.1+, scoped registries can be directly edited via Project Settings/Package Manager, so the menu item now forwards to there.

Also fixes #14 by asking for editor restart when adding or changing credentials. This could be improved a bit by investigating on which versions Unity needs to be restarted and when a PackMan resolve or reload suffice.

2020-11-02 13:07 UTC, jespersmith commented
Thank you for your PR. It's busy here so I'll need a few days to review and merge.

2020-11-09 09:31 UTC, jespersmith commented
The improved user errors are super helpful.

One comment/discussion point:
The scoped registries editor builtin Unity does not allow setting credentials. It is easier for the user if that can be done in the same dialog I think. We're not sure if reducing custom dialogs weighs up to the slightly more complicated user experience. What is your reasoning behind using the builtin Unity UI's?

2020-11-09 09:34 UTC, jespersmith requested changes
The UI improvements are worth it. I've to think a little about using the builtin Unity registry editor directly.

2020-11-09 16:22 UTC, hybridherbst commented
Ah, I think I should have mentioned, this goes together with #17, and also some additional changes I haven't made a PR for yet.

Together, these make the menu items basically obsolete, and use the `Project Settings/Package Manager` area for everything related to packages, which I think is easier to find than menu items.

Looks like this:
![image](https://user-images.githubusercontent.com/2693840/98567088-d5694800-22af-11eb-9cd0-c34abebf6d8c.png)

Pressing "Edit" leads to the registry window in "edit" mode:
![image](https://user-images.githubusercontent.com/2693840/98567222-f893f780-22af-11eb-8550-c4c5f224f2ef.png)

And pressing "+" to the registry window in "add" mode as you had:
![image](https://user-images.githubusercontent.com/2693840/98567289-0a759a80-22b0-11eb-9f63-e99beb82f3cd.png)

I'll make sure to PR the other changes – they individually make sense but I think together work best :)

2020-11-09 18:11 UTC, jespersmith commented
That's a great improvement, I'm looking forward to it. For 2019.4 we can leave a simple link to the old registry manager in the Package Manager section

2020-11-09 18:12 UTC, merged